### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by pagomide** [Riron/ionic-img-viewer#103]
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          | 3.9.2
angular         | 4.1.3
ionic-img-viewer|2.9.0

### Have you checked...
- [x] That npm install returns no warning ?
- [ ] Doing a purge of your node_modules folder ?

> Error: Metadata version mismatch for module /dir/node_modules/ionic-img-viewer/dist/es2015/src/module.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/dir/node_modules/@angular/compiler/bundles/compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (/dir/node_modules/@angular/compiler/bundles/compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (/dir/@angular/compiler/bundles/compiler.umd.js:25385:14)
    at /dir/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (/dir/node_modules/@angular/compiler/bundles/compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (/dir/node_modules/@angular/compiler/bundles/compiler.umd.js:23796:47)
    at CodeGenerator.codegen (/dir/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/dir/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at /dir/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:182:73

**Comment by anjoseb121** [comment]
That just happened to me running `ionic cordova run android --prod`

**Comment by sydtpt** [comment]
Same problem.
ionic-angular: 3.9.2
angular: 4.3.6
ionic-img-viewer: 2.9.0

output:
Error: Metadata version mismatch for module /Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/ionic-img-viewer/dist/es2015/src/module.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler/bundles/compiler.umd.js:25586:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler/bundles/compiler.umd.js:25374:46)
    at StaticSymbolResolver.getSymbolsOf (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler/bundles/compiler.umd.js:25355:14)
    at /Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler/bundles/compiler.umd.js:24214:30
    at Array.forEach (native)
    at extractProgramSymbols (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler/bundles/compiler.umd.js:24213:79)
    at AotCompiler.analyzeModulesAsync (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler/bundles/compiler.umd.js:23771:47)
    at CodeGenerator.codegen (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at Object.doCodegen (/Users/sydnei.tanikawa/dev/Meus Ativos Fixos/app/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:51)

**Comment by Riron** [comment]
`ionic-angular@3.9.x` must be used with `angular@5.x` and not `4.x`. The same goes for `ionic-img-viewer@2.9.x`. That's probably why

**Comment by bhavinwebdesk** [comment]
@Riron  so what is the solution? Should I upgrade to angular@5.x?

**Comment by Riron** [comment]
Yes, please upgrade

**Comment by codinronan** [comment]
@Riron you need to pull version 2.9 and do a major version bump up to 3 if you are going to move to Angular 5. Angular 5 is mildly incompatible with Angular 4 and it is NOT POSSIBLE to mix them - that is why the Angular team bumped the metadata version from 3 to 4.

**Comment by selected-pixel-jameson** [comment]
Pretty sure that ionic-angular@3.9.x is unstable at this point and can't even be installed. https://github.com/ionic-team/ionic/issues/13385

**Comment by Riron** [comment]
Yes you need Angular 5.
I chose to follow Ionic versioning system and not Angular.
Ionic did not do a major version bump. Even if that's questionable, i'll stick with this for now.
