### ISSUE TITLE
build prod failed: can't find symbol KeyRegistry exported from module

### ISSUE THREAD

**Issue by vsrboth** [Riron/ionic-img-viewer#53]
I encounter this bug with the build command `ionic build android --prod`.

ionic2: v2.2.1
ionic-img-viewer: v1.3.2

[10:53:22]  build prod failed: can't find symbol KeyRegistry exported from module
            /private/var/www/experiment/MotionscloudWebrtc/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts
[10:53:22]  ionic-app-script task: "build"
[10:53:22]  Error: can't find symbol KeyRegistry exported from module
            /private/var/www/experiment/MotionscloudWebrtc/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts
Error: can't find symbol KeyRegistry exported from module /private/var/www/experiment/MotionscloudWebrtc/node_modules/ionic-img-viewer/node_modules/@angular/core/src/di/reflective_key.d.ts

**Comment by vishaltechreceptives** [comment]
face issue in build prod mode.

ionic2: v2.2.1
ionic-img-viewer: v1.3.3

can't resolve module ./image-viewer-transitions from /home/erp/Mobile_app/ionic-sales-app/node_modules/ionic-img-viewer/dist/src/module.d.ts
[12:24:30]  build prod failed: Cannot read property 'registerCustomTransitions' of undefined, resolving symbol 
            IonicImageViewerModule in 
            /home/erp/Mobile_app/ionic-sales-app/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving symbol 
            IonicImageViewerModule in 
            /home/erp/Mobile_app/ionic-sales-app/node_modules/ionic-img-viewer/dist/src/module.d.ts 
[12:24:30]  ionic-app-script task: "build" 
[12:24:30]  Error: Cannot read property 'registerCustomTransitions' of undefined, resolving symbol 
            IonicImageViewerModule in 
            /home/erp/Mobile_app/ionic-sales-app/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving symbol 
            IonicImageViewerModule in 
            /home/erp/Mobile_app/ionic-sales-app/node_modules/ionic-img-viewer/dist/src/module.d.ts 
Error: Cannot read property 'registerCustomTransitions' of undefined, resolving symbol IonicImageViewerModule in /home/erp/Mobile_app/ionic-sales-app/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving symbol IonicImageViewerModule in /home/erp/Mobile_app/ionic-sales-app/node_modules/ionic-img-viewer/dist/src/module.d.ts
    at simplifyInContext (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/home/erp/Mobile_app/ionic-sales-app/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)

**Comment by Riron** [comment]
@vishaltechreceptives why are you posting on this thread ? It doesn't look like it's the same error. Please open another issue.

@vsrboth you have a dependencies problem, you should not have a `node_modules` folder inside of the `ionic-img-viewer` folder (cf `/node_modules/ionic-img-viewer/node_modules/@angular/core/...`). Try to re install you dependencies and update to `ionic-img-viewer@1.3.3` or `ionic-img-viewer@1.3.4`, that should help you as peer dependecies are declared.
